trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.10'
    displayName: 'Set up Python'

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: |
      python app.py
    displayName: 'Run application'

  - script: |
      python -m pytest -v --junitxml=test-results.xml
    displayName: 'Run unit tests'

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/test-results.xml'
      failTaskOnFailedTests: true
    condition: succeededOrFailed()
    displayName: 'Publish test results'

  
  - task: AzureCLI@2
    displayName: 'Build and push Docker image to ACR'
    inputs:
      azureSubscription: 'sc-azure-acr-raiacontainer310'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az acr login --name raiacontainer310
        docker build -t raiacontainer310.azurecr.io/cloud-migration-app:$(Build.BuildId) .
        docker push raiacontainer310.azurecr.io/cloud-migration-app:$(Build.BuildId)

